# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'complex.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainn_windoww(object):
    def setupUi(self, mainn_windoww):
        mainn_windoww.setObjectName("mainn_windoww")
        mainn_windoww.resize(969, 564)
        mainn_windoww.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(63, 119, 226, 240), stop:1 rgba(255, 255, 255, 255));")
        self.pushButton = QtWidgets.QPushButton(mainn_windoww)
        self.pushButton.setGeometry(QtCore.QRect(740, 480, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(mainn_windoww)
        self.pushButton_2.setGeometry(QtCore.QRect(70, 480, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(mainn_windoww)
        self.label.setGeometry(QtCore.QRect(100, 40, 781, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(26)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_question = QtWidgets.QLabel(mainn_windoww)
        self.label_question.setGeometry(QtCore.QRect(110, 130, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_question.setFont(font)
        self.label_question.setObjectName("label_question")
        self.label_question_2 = QtWidgets.QLabel(mainn_windoww)
        self.label_question_2.setGeometry(QtCore.QRect(100, 170, 831, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_question_2.setFont(font)
        self.label_question_2.setText("")
        self.label_question_2.setObjectName("label_question_2")
        self.widget = QtWidgets.QWidget(mainn_windoww)
        self.widget.setGeometry(QtCore.QRect(100, 220, 801, 191))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.rdb_answer_one = QtWidgets.QRadioButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.rdb_answer_one.setFont(font)
        self.rdb_answer_one.setText("")
        self.rdb_answer_one.setObjectName("rdb_answer_one")
        self.verticalLayout.addWidget(self.rdb_answer_one)
        self.rdb_answer_two = QtWidgets.QRadioButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.rdb_answer_two.setFont(font)
        self.rdb_answer_two.setText("")
        self.rdb_answer_two.setObjectName("rdb_answer_two")
        self.verticalLayout.addWidget(self.rdb_answer_two)
        self.rdb_answer_three = QtWidgets.QRadioButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.rdb_answer_three.setFont(font)
        self.rdb_answer_three.setText("")
        self.rdb_answer_three.setObjectName("rdb_answer_three")
        self.verticalLayout.addWidget(self.rdb_answer_three)

        self.retranslateUi(mainn_windoww)
        QtCore.QMetaObject.connectSlotsByName(mainn_windoww)

    def retranslateUi(self, mainn_windoww):
        _translate = QtCore.QCoreApplication.translate
        mainn_windoww.setWindowTitle(_translate("mainn_windoww", "Dialog"))
        self.pushButton.setText(_translate("mainn_windoww", "Начать"))
        self.pushButton_2.setText(_translate("mainn_windoww", "Дальше"))
        self.label.setText(_translate("mainn_windoww", "Тест по CompexObject and ComplexSubject"))
        self.label_question.setText(_translate("mainn_windoww", "Вопрос:"))
    def function(self):
        with open("C:\\Temp\\kaka.json","r", encoding="utf-8") as my_file:
            self.data = json.load(my_file)
        self.label.setText(self.data["вопросы"][self.k]["Вариант ответа 1"])
        self.label_2.setText(self.data["вопросы"][self.k]["Вариант ответа 1"])
        self.label_3.setText(self.data["вопросы"][self.k]["Вариант ответа 1"])
        self.label_4.setText(self.data["вопросы"][self.k]["Правильный ответ"])
        self.k+=1
        self.pushButton.clicked.connect(self.nextt)
    def nextt(self):
        self.label.setText(self.data["вопросы"][self.k]["Вариант ответа 1"])
        self.label_2.setText(self.data["вопросы"][self.k]["Вариант ответа 1"])
        self.label_3.setText(self.data["вопросы"][self.k]["Вариант ответа 1"])
        self.label_4.setText(self.data["вопросы"][self.k]["Правильный ответ"])
        self.k +=1

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainn_windoww = QtWidgets.QDialog()
    ui = Ui_mainn_windoww()
    ui.setupUi(mainn_windoww)
    mainn_windoww.show()
    sys.exit(app.exec_())
